package com.iup.tp.twitup.core.viewControllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;

public class LogController {

	@FXML
	private AnchorPane AccueilComponent;
	@FXML
	private GridPane SwitchComponent;
	@FXML
	private Button btnSwitchConnexion;
	@FXML
	private Button btnSwitchInscription;
	@FXML
	private AnchorPane AnchorContainerLog;
	@FXML
	private Pane InscriptionConmponent;
	@FXML
	private Button btnInscription;
	@FXML
	private PasswordField fieldPwdInscription;
	@FXML
	private TextField fieldTagInscription;
	@FXML
	private TextField fieldLoginInscription;
	@FXML
	private GridPane ConnexionComponent;
	@FXML
	private Button btnConnexion;
	@FXML
	private PasswordField fieldPwdConnexion;
	@FXML
	private TextField fieldLoginConnexion;

	// Event Listener on Button[#btnSwitchConnexion].onAction
	@FXML
	public void onBtnSwitchConnexionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSwitchInscription].onAction
	@FXML
	public void onBtnSwitchInscriptionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInscription].onAction
	@FXML
	public void onBtnInscriptionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConnexion].onAction
	@FXML
	public void onBtnConnexionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	public AnchorPane getComponent() {
		// TODO Auto-generated method stub
		return AccueilComponent;
	}
}
