package com.iup.tp.twitup.core.viewControllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;

public class MainController {
	@FXML
	private BorderPane MainComponent;
	@FXML
	private GridPane GridPaneAccueilLeft;
	@FXML
	private Button btnAccueil;
	@FXML
	private Button btnUsers;
	@FXML
	private Button btnProfile;
	@FXML
	private Button btnNewTweet;
	@FXML
	private Button btnResearch;
	@FXML
	private Button btnDisconnect;
	@FXML
	private Pane PaneAccueilCenter;
	@FXML
	private Pane PaneAccueilRight;

	// Event Listener on Button[#btnAccueil].onAction
	@FXML
	public void onBtnAccueilAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUsers].onAction
	@FXML
	public void onBtnUtsersAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnProfile].onAction
	@FXML
	public void onBtnProfileAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewTweet].onAction
	@FXML
	public void onBtnNewTweetAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnResearch].onAction
	@FXML
	public void onBtnResearchAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDisconnect].onAction
	@FXML
	public void onBtnDisconnectAction(ActionEvent event) {
		// TODO Autogenerated
	}
	public void setCenter(AnchorPane component) {
		// TODO Auto-generated method stub
		PaneAccueilCenter.getChildren().add(component);
	}
	

}
