package com.iup.tp.twitup.core.viewControllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;

public class NewTweetController {
	@FXML
	private AnchorPane NewTweetComponent;
	@FXML
	private Button btnNewTweet;

	// Event Listener on Button[#btnNewTweet].onAction
	@FXML
	public void onBtnNewTweetAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
