package com.iup.tp.twitup.core;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.PasswordField;

import javafx.scene.layout.Pane;

public class FXMLController {
	@FXML
	private AnchorPane AccueilComponent;
	@FXML
	private Pane SwitchComponent;
	@FXML
	private Button btnSwitchConnexion;
	@FXML
	private Button btnSwitchInscription;
	@FXML
	private Pane ConnexionComponent;
	@FXML
	private Button btnConnexion;
	@FXML
	private PasswordField fieldPwdConnexion;
	@FXML
	private TextField fieldLoginConnexion;
	@FXML
	private Pane InscriptionConmponent;
	@FXML
	private Button btnInscription;
	@FXML
	private PasswordField fieldPwdInscription;
	@FXML
	private TextField fieldTagInscription;
	@FXML
	private TextField fieldLoginInscription;

	private void changeLogPan(Pane pane){
		
	}
	// Event Listener on Button[#btnSwitchConnexion].onAction
	@FXML
	public void onBtnSwitchConnexionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSwitchInscription].onAction
	@FXML
	public void onBtnSwitchInscriptionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnConnexion].onAction
	@FXML
	public void onBtnConnexionAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInscription].onAction
	@FXML
	public void onBtnInscriptionAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
